# fcrontab
# Autogenerated from man page /usr/share/man/man1/fcrontab.1.gz
complete -c fcrontab -s u --description 'Specify the user whose fcrontab will be managed, or "systab" for the system f…'
complete -c fcrontab -s l --description 'List user\'s current fcrontab to standard output.'
complete -c fcrontab -s e --description 'Edit user\'s current fcrontab using either the editor specified by the environ…'
complete -c fcrontab -s r --description 'Remove user\'s fcrontab.'
complete -c fcrontab -s z --description 'Reinstall user\'s fcrontab from its source code.'
complete -c fcrontab -s n --description 'Ignore previous version.'
complete -c fcrontab -s c --description 'Make fcrontab use config file file instead of default config file /usr/local/…'
complete -c fcrontab -s d --description 'Run in debug mode.'
complete -c fcrontab -s h --description 'Display a brief description of the options.'

