# fcrondyn
# Autogenerated from man page /usr/share/man/man1/fcrondyn.1.gz
complete -c fcrondyn -s i --description 'Run fcrondyn in interactive mode.'
complete -c fcrondyn -s x --description 'Run command and returns immediately.'
complete -c fcrondyn -s c --description 'Make fcrondyn use config file file instead of default config file /usr/local/…'
complete -c fcrondyn -s d --description 'Run in debug mode.'
complete -c fcrondyn -s h --description 'Display a brief description of the options.'

